# Generated by Django 5.1.2 on 2024-11-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='color_favorito',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_captura',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
